# Generated by Django 4.0.4 on 2022-06-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aslapp', '0003_alter_image_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageSet',
        ),
        migrations.RenameField(
            model_name='imageset',
            old_name='image',
            new_name='img',
        ),
    ]
